
version: '3'

services:
  wordpress:
    image: wordpress:fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariad
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: 030718110
    volumes:
      -

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
   
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot
    command: certonly
